name: Build Mikrotik RSC

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Fetch original hosts
        run: |
          curl -sSL -o hosts \
            https://raw.githubusercontent.com/pumPCin/AntiZapret/main/hosts

      - name: Generate update-hosts.rsc
        run: |
          mkdir -p mikrotik
          echo "/ip dns static remove [find address-list=\"autohost\"]" \
            > mikrotik/update-hosts.rsc
          cnt=0

          while read -r ip rest; do
            for d in $rest; do
              # пропускаем локал/броадкаст
              if [[ "$ip" == "127.0.0.1" && ( "$d" == "local" || "$d" == "localhost" || "$d" == "localhost.localdomain" ) ]]; then
                continue
              fi
              if [[ "$ip" == "255.255.255.255" && "$d" == "broadcasthost" ]]; then
                continue
              fi

              # 0.0.0.0 → черная дыра в TEST-NET-1
              if [[ "$ip" == "0.0.0.0" ]]; then
                ip_addr="192.0.2.1"
              else
                ip_addr="$ip"
              fi

              echo "/ip dns static add name=$d address=$ip_addr ttl=1d address-list=autohost" \
                >> mikrotik/update-hosts.rsc
              cnt=$((cnt+1))
            done
          done < <(grep -Ev '^(#|$)' hosts)

          echo "/log info \"[update-hosts] Added $cnt entries\"" \
            >> mikrotik/update-hosts.rsc
          echo ":: Generated $cnt entries"

      - name: Commit & Push update-hosts.rsc
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add mikrotik/update-hosts.rsc
          git diff --quiet --cached || git commit -m "Rebuild Mikrotik RSC: $cnt entries"
          git push
