name: Build Mikrotik RSC

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate update-hosts.rsc
        run: |
          mkdir -p mikrotik
          echo "/ip dns static remove [find comment=\"autohost\"]" > mikrotik/update-hosts.rsc
          cnt=0
          # парсим оригинальный hosts
          grep -Ev '^(#|$)' hosts | while read ip rest; do
            for d in $rest; do
              echo "/ip dns static add name=$d address=$ip ttl=1d comment=\"autohost\"" \
                >> mikrotik/update-hosts.rsc
              ((cnt++))
            done
          done
          echo "/log info \"[update-hosts] Added $cnt entries\"" \
            >> mikrotik/update-hosts.rsc
          echo ":: Generated $cnt entries"
